version: "3.7"
services:
  mysql:
    image: "mysql:8.0.17"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: "redis:5.0.5-alpine"
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

# TODO
# react app config Pending
#  frontend:
#    build:
#      context: ../gamedoora-frontend
#
#    depends_on:
#      - "mysql"
#      - "redis"
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/patakafrontend
#    restart: always
#    links:
#      - redis
#      - mysql

  api:
    build:
      context: ../gamedoora-backend
    depends_on:
      - "mysql"
      - "redis"
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: gamedoora-backend_development
      DB_PORT: 3306
      DB_HOST: mysql
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    volumes:
      - .:/api
    restart: always
    links:
      - redis
      - mysql

  sidekiq:
    depends_on:
      - "mysql"
      - "redis"
    build: ../gamedoora-backend
    command: sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: gamedoora-backend_development
      DB_PORT: 3306
      DB_HOST: mysql
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/api"


volumes:
  api: {}
  redis: {}
  database: {}
